More work on generics

diff --git a/run-all-tests b/run-all-tests
--- a/run-all-tests
+++ b/run-all-tests
@@ -9,3 +9,13 @@ for filename in ./tests/cli/*.chy; do
     ./zig-out/bin/cherry "$filename" > /dev/null \
         || die "Failed test $filename"
 done
+
+for filename in ./tests/cli/semantics/*.chy; do 
+    ./zig-out/bin/cherry --types "$filename" > /dev/null \
+        || die "Failed test $filename"
+done
+
+for filename in ./tests/cli/semantics/failures/*.chy; do 
+    ./zig-out/bin/cherry --types "$filename" > /dev/null \
+        && die "Failed test $filename"
+done
